# Generated by Django 5.1.6 on 2025-02-28 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, null=True)),
                ('p_name', models.CharField(max_length=50, null=True)),
                ('rate', models.CharField(max_length=50, null=True)),
                ('book_amt', models.CharField(max_length=50, null=True)),
                ('tamount', models.CharField(max_length=50, null=True)),
                ('balance', models.CharField(max_length=50, null=True)),
                ('nxt_dt', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('ph', models.CharField(max_length=50, null=True)),
                ('bill_no', models.CharField(max_length=50, null=True)),
                ('flt', models.CharField(max_length=50, null=True)),
                ('del_status', models.CharField(max_length=50, null=True)),
                ('dt', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df', models.CharField(max_length=50, null=True)),
                ('dt', models.DateField()),
                ('fname', models.CharField(max_length=200, null=True)),
                ('mname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('ph', models.CharField(max_length=200, null=True)),
                ('mail', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('nam', models.CharField(max_length=200, null=True)),
                ('relation', models.CharField(max_length=200, null=True)),
                ('raddress', models.CharField(max_length=200, null=True)),
                ('paddress', models.CharField(max_length=200, null=True)),
                ('adhar', models.CharField(max_length=200, null=True)),
                ('exname', models.CharField(max_length=200, null=True)),
                ('maname', models.CharField(max_length=200, null=True)),
                ('tname', models.CharField(max_length=200, null=True)),
                ('p_mode', models.CharField(max_length=200, null=True)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('layout', models.CharField(max_length=200, null=True)),
                ('nxt_dt', models.CharField(max_length=200, null=True)),
                ('p_name', models.CharField(max_length=50, null=True)),
                ('flt', models.CharField(max_length=50, null=True)),
                ('sqft', models.CharField(max_length=50, null=True)),
                ('rate', models.CharField(max_length=50, null=True)),
                ('tamount', models.CharField(max_length=50, null=True)),
                ('book_amt', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('mname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('ph', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('nam', models.CharField(max_length=200, null=True)),
                ('relation', models.CharField(max_length=200, null=True)),
                ('raddress', models.CharField(max_length=200, null=True)),
                ('paddress', models.CharField(max_length=200, null=True)),
                ('adhar', models.CharField(max_length=200, null=True)),
                ('p_name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_name', models.CharField(max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incntive_executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('ex_name', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=50, null=True)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager_executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('manager_name', models.CharField(max_length=50, null=True)),
                ('remark', models.CharField(max_length=50, null=True)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('fname', models.CharField(max_length=50, null=True)),
                ('p_name', models.CharField(max_length=50, null=True)),
                ('flt', models.CharField(max_length=50, null=True)),
                ('bill_no', models.CharField(max_length=50, null=True)),
                ('ph', models.CharField(max_length=50, null=True)),
                ('executive_name', models.CharField(max_length=50, null=True)),
                ('manager_name', models.CharField(max_length=50, null=True)),
                ('tel_name', models.CharField(max_length=50, null=True)),
                ('p_mode', models.CharField(max_length=50, null=True)),
                ('paddress', models.CharField(max_length=50, null=True)),
                ('book_amt', models.CharField(max_length=50, null=True)),
                ('nxt_dt', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('rate', models.CharField(max_length=50, null=True)),
                ('tamount', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, null=True)),
                ('flt', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelliCaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_name', models.CharField(max_length=50, null=True)),
                ('phone_no', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tellicaller_executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('tell_name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('amount', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
