# Generated by Django 5.1.6 on 2025-02-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_master',
            name='del_status',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing_master',
            name='status',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
