# Generated by Django 5.1.6 on 2025-03-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_billing_master_del_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_master',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='book_amt',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='del_status',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='flt',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='nxt_dt',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='status',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='tamount',
        ),
    ]
