# Generated by Django 5.1.6 on 2025-03-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_billing_master_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_master',
            name='balance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='bill_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='book_amt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='del_status',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='dt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='flt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='nxt_dt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='p_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='ph',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='rate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='status',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='billing_master',
            name='tamount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
