# Generated by Django 5.1.6 on 2025-03-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_billing_master_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_master',
            name='del_status',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing_master',
            name='status',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
    ]
